import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Layout } from "@/components/layout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(get_t, r, a, k, t, c, o) {
                get_t['TrackingID'] = t;
                get_t[t] = get_t[t] || function() {
                (get_t[t].q = get_t[t].q || []).push(arguments)
                }, get_t[t].l = 1 * new Date();
                c = r.createElement(a),
                o = r.getElementsByTagName(a)[0];
                c.async = 1;
                c.src = k + '?id=' + t;
                o.parentNode.insertBefore(c, o)
              })(window, document, 'script', 'https://dev.connector.trakt.pro/tracking.js', 'U30VR31TED&url=https://dev.api.pro-crm.trakt.pro/api');
            `,
          }}
        />
      </head> */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <form 
          method="post" 
          name="contact-form" 
          id="contact-form" 
          data-track-form="true"
          className="elementor-form"
        >
          <div className="elementor-form-fields-wrapper">
            <div className="elementor-field-group">
              <label htmlFor="name">Full Name</label>
              <input 
                type="text" 
                name="form_fields[name]" 
                id="name" 
                className="elementor-field"
              />
            </div>
            <div className="elementor-field-group">
              <label htmlFor="email">Email</label>
              <input 
                type="email" 
                name="form_fields[email]" 
                id="email" 
                className="elementor-field"
                required
              />
            </div>
            <div className="elementor-field-group">
              <label htmlFor="message">Message</label>
              <textarea 
                name="form_fields[message]" 
                id="message" 
                className="elementor-field"
                rows={4}
              />
            </div>
            <div className="elementor-field-group">
              <button type="submit" className="elementor-button">
                Send
              </button>
            </div>
          </div>
        </form> */}
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
