import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Layout } from '@/components/layout';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(get_t, r, a, k, t, c, o) {
                get_t['TrackingID'] = t;
                get_t[t] = get_t[t] || function() {
                  (get_t[t].q = get_t[t].q || []).push(arguments)
                }, get_t[t].l = 1 * new Date();
                c = r.createElement(a),
                o = r.getElementsByTagName(a)[0];
                c.async = 1;
                c.src = k + '?id=' + t;
                o.parentNode.insertBefore(c, o)
              })(window, document, 'script', 'https://app.trakt.pro:8443/tracking.js', 'RC910SPQSH');
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
